<!DOCTYPE html>
<html lang="en-US">
<!--********************************************-->
<!--*       Generated from PreTeXt source      *-->
<!--*                                          *-->
<!--*         https://pretextbook.org          *-->
<!--*                                          *-->
<!--********************************************-->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="robots" content="noindex, nofollow">
</head>
<body class="ignore-math">
<h4 class="heading"><span class="type">Paragraph</span></h4>
<div class="para">Let’s add a finally-block to <a href="" class="xref" data-knowl="./knowl/listing-ex-extest2.html" title="Listing 11.3.4">Listing 11.3.4</a> and test our new program, both with a statement that throws an exception and with a statement that succeeds.</div>
<span class="incontext"><a href="section-ex-catching.html#p-851" class="internal">in-context</a></span>
</body>
</html>
